version: '3.2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app-ui:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    ports:
      - "3005"
    environment:
      - INSTANCE=app-service
  app-service:
    build:
      context: services/app-service
      dockerfile: Dockerfile
    ports:
      - "3006"
  video-service:
    build:
      context: services/app-service
      dockerfile: Dockerfile
    ports:
      - "3007"
  nginx:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    depends_on:
      - builder-server
    ports:
      - "8080:80"
    links:
      - builder-server:builder-server
    restart: always